name: dependencies
description: All dependencies of project
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  #Core 
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  
  meta: ^1.7.0
  logger: ^1.0.0
  dartz: ^0.9.2
  # rxdart: ^0.25.0
  #Core-End

  #Networking
  dio: ^4.0.0
  # retrofit: ^2.0.1
  #Networking-End
  
  #Data
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6
  floor: ^1.1.0
  #Data-End

  #UI
  # intro_slider: ^2.4.1
  # convex_bottom_bar: ^3.0.0
  # fl_chart: ^0.36.0
  # flutter_hooks: ^0.18.0
  # shimmer: ^1.1.2
  # cached_network_image: ^2.5.0
  # url_launcher: ^5.7.10
  # flutter_launcher_icons: ^0.8.1
  # package_info: ^0.4.3+2
  # flutter_svg: ^0.19.3
  # liquid_pull_to_refresh: ^2.0.0
  # carousel_slider: ^3.0.0
  # lottie: ^0.7.0+1
  # fluttertoast: ^7.1.5
  #UI-End


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
